### ISSUE TITLE
Logging in 

### ISSUE THREAD

**Issue by SeriousHamburger** [ZombieAlex/mfcauto.py#6]
After logging in to a premium account using either `SimpleClient` or `Client` I get
```
Unexpected exception: <class 'IndexError'>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\mfcauto\client.py", line 60, in data_received
    self.client.handle_packet_received(Packet(*unpacked_data[1:-1], smessage))
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\mfcauto\client.py", line 90, in handle_packet_received
    self._process_packet(packet)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\mfcauto\client.py", line 147, in _process_packet
    rdata = self._process_list(packet.smessage["rdata"])
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\mfcauto\client.py", line 235, in _process_list
    schema = data[0]
IndexError: list index out of range
```

**Comment by SeriousHamburger** [comment]
I've tested this with 2 different accounts and have tried it using the examples in test, after the login successful message appears it throws this exception.

**Comment by ZombieAlex** [comment]
Thanks for the report. That wasn't happening to me, but the call stack was enough to track down the obvious bug. Found and fixed another bug in the same function while I was at it.

Keep in mind that to log in you won't be using your plain text password, you'll be using MFC's hash of your password. See the [notes from my NodeJS version of this code](https://github.com/ZombieAlex/MFCAuto/blob/master/src/main/Client.ts#L48).
